name: IconManager
author: drtshock
version: ${project.version}
main: io.snw.iconmanager.IconManager
commands:
  iconmanager:
    description: Default command for IconManager
    permission: iconmanager.admin
    usage: /<command> <reload | info>

    